[project]
name = "xinject"
version = "1.11.0"
description = "Lazy dependency injection."
authors = [{ name = "Josh Orr", email = "josh@orr.blue" }]
requires-python = ">=3.14,<4"
readme = "README.md"
keywords = [
    "dependency",
    "injection",
    "lazy",
    "resource",
]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["xsentinels>=1.2.0,<2"]

[project.urls]
Repository = "https://github.com/xyngular/py-xinject"

[project.entry-points.pytest11]
xinject_pytest_plugin = "xinject.pytest_plugin"

[dependency-groups]
dev = [
    "mkdocs-git-revision-date-plugin>=0.3.2,<0.4",
    "mkdocs>=1.4.0,<2",
    "mike>=2,<3",
    "pytest-pycodestyle>=2.3.0,<3",
    "pytest>=9,<10",
    "pdoc3>=0,<1",
    "mkdocs-material>=9,<10",
    "tomlkit>=0,<1",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["xinject"]
module-root = ""

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --pycodestyle"
testpaths = ["tests", "xinject"]

[tool.custom.xpublish]
extra-module-docs = ['xsentinels']

[tool.black]
line-length = 119
skip-string-normalization = 1
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
